migrate(
  (app) => {
    // Create Admin User
    const users = app.findCollectionByNameOrId('_pb_users_auth_')
    const user = new Record(users)
    user.setEmail('wagner@pelaspanelas.com.br')
    user.setPassword('securepassword123')
    user.setVerified(true)
    user.set('role', 'Admin')
    user.set('name', 'Wagner Admin')
    app.save(user)

    // Create Banks
    const banksCol = app.findCollectionByNameOrId('banks')
    const bank1 = new Record(banksCol)
    bank1.set('name', 'NuBank')
    bank1.set('account_number', '0001-1')
    app.save(bank1)
    const bank2 = new Record(banksCol)
    bank2.set('name', 'Itaú')
    bank2.set('account_number', '0002-2')
    app.save(bank2)
    const bank3 = new Record(banksCol)
    bank3.set('name', 'Inter')
    bank3.set('account_number', '0003-3')
    app.save(bank3)

    // Create Transactions
    const transCol = app.findCollectionByNameOrId('transactions')
    const now = new Date()

    // Distribute dates slightly in the past
    const d1 = new Date(now)
    d1.setDate(d1.getDate() - 1)
    const d2 = new Date(now)
    d2.setDate(d2.getDate() - 2)
    const d3 = new Date(now)
    d3.setDate(d3.getDate() - 3)
    const d4 = new Date(now)
    d4.setDate(d4.getDate() - 5)
    const d5 = new Date(now)
    d5.setDate(d5.getDate() - 10)

    const t1 = new Record(transCol)
    t1.set('user_id', user.id)
    t1.set('date', d1.toISOString())
    t1.set('description', 'Salário Mensal')
    t1.set('amount', 8500)
    t1.set('type', 'entrada')
    t1.set('bank', bank1.id)
    app.save(t1)
    const t2 = new Record(transCol)
    t2.set('user_id', user.id)
    t2.set('date', d2.toISOString())
    t2.set('description', 'Aluguel')
    t2.set('amount', 2200)
    t2.set('type', 'saída')
    t2.set('bank', bank2.id)
    app.save(t2)
    const t3 = new Record(transCol)
    t3.set('user_id', user.id)
    t3.set('date', d3.toISOString())
    t3.set('description', 'Supermercado')
    t3.set('amount', 850)
    t3.set('type', 'saída')
    t3.set('bank', bank1.id)
    app.save(t3)
    const t4 = new Record(transCol)
    t4.set('user_id', user.id)
    t4.set('date', d4.toISOString())
    t4.set('description', 'Projeto Freelance')
    t4.set('amount', 3000)
    t4.set('type', 'entrada')
    t4.set('bank', bank3.id)
    app.save(t4)
    const t5 = new Record(transCol)
    t5.set('user_id', user.id)
    t5.set('date', d5.toISOString())
    t5.set('description', 'Energia e Internet')
    t5.set('amount', 350)
    t5.set('type', 'saída')
    t5.set('bank', bank2.id)
    app.save(t5)
  },
  (app) => {
    try {
      const user = app.findAuthRecordByEmail('_pb_users_auth_', 'wagner@pelaspanelas.com.br')
      app.delete(user)
    } catch (e) {}

    app.truncateCollection(app.findCollectionByNameOrId('banks'))
    app.truncateCollection(app.findCollectionByNameOrId('transactions'))
  },
)
